spring:
  application:
    name: eurekaserver
---
server:
  port: 10086
spring:
  profiles: eureka-server1
eureka:
  instance:
    hostname: 10.14.0.62
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.14.0.64:10086/eureka/
---
server:
  port: 10086
spring:
  profiles: eureka-server2
eureka:
  instance:
    hostname: 10.14.0.64
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.14.0.62:10086/eureka/