server:
  port: 8761

spring:
  application:
    name: eureka-server01

eureka:
#集群版
#  instance:
#    hostname: eureka01
#    prefer-ip-address: true   #是否使用ip地址注册
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #ip:port   ${spring.cloud.client.ip-address}
#  client:
#    register-with-eureka: false #服务端必配，禁止自动注册
#    fetch-registry: false #服务端必配，表示自己就是注册中心，不需要去检索服务
#    # 指向另外一个注册中心，
#    service-url:   #注册中心对外暴露的注册地址
#      defaultZone: http://localhost:8762/eureka/
#单机版
  instance:
    hostname: eureka01
    prefer-ip-address: true   #是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #ip:port   ${spring.cloud.client.ip-address}
  client:
    register-with-eureka: false #服务端必配，禁止自动注册
    fetch-registry: false #服务端必配，表示自己就是注册中心，不需要去检索服务
    service-url:   #注册中心对外暴露的注册地址
      defaultZone: http://10.14.0.62:${server.port}/eureka/
#      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护

