# 集群版
spring:
  application:
    name: EUREKA-HA

---
server:
  port: 10086
spring:
  # 指定profile=eureka-server1
  profiles: eureka-server1
eureka:
  instance:
    # 指定当profile=eureka-server1时，主机名是eureka-server1
    hostname: 10.14.0.62
    prefer-ip-address: true   #是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false #服务端必配，禁止自动注册
    fetch-registry: false #服务端必配，表示自己就是注册中心，不需要去检索服务
    service-url:
      # 将自己注册到eureka-server1、eureka-server2这个Eureka上面去
      defaultZone: http://10.14.0.62:10086/eureka/,http://110.14.0.64:10086/eureka/

---
server:
  port: 10086
spring:
  profiles: eureka-server2
eureka:
  instance:
    hostname: 10.14.0.64
    prefer-ip-address: true   #是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false #服务端必配，禁止自动注册
    fetch-registry: false #服务端必配，表示自己就是注册中心，不需要去检索服务
    service-url:
      defaultZone: http://10.14.0.62:10086/eureka/,http://10.14.0.64:10086/eureka/