---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: NodePort
  ports:
    - port: 9002
      name: product-service
      targetPort: 9002
  selector:
    app: product-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-service
spec:
  serviceName: "product-service"
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: product-service
          image: $IMAGE_NAME
          ports:
            - containerPort: 9002
  podManagementPolicy: "Parallel"