server:
  port: 9001 #端口

spring:
  application:
    name: gateway-server-sentinel
  cloud:
    sentinel:
      filter:
        enabled: false   #将网关的资源不展示在sentinel上控制
    gateway:
      discovery:
        locator:
          # 是否与服务发现组建进行组合，通过serviceID转发到具体服务实例
          enabled: true               #是否开启基于服务发现的路由规则
          lower-case-service-id: true #是否将服务名称转为小写
      # 配置路由规则，可以配置多个
      routes:
        - id: order-service  # id 自定义路由的id
          uri: lb://order-service  # lb:// 根据负载均衡去注册中心获取微服务请求地址
          predicates:   # 断言
            - Path=/order/** # 匹配对应的url的请求，将匹配的请求追加在目标uri之后

#配置Eureka注册中心
eureka:
  instance:
    prefer-ip-address: true   #是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #ip:port
  client:
    service-url:   #设置注册中心地址
#集群版注册中心
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#单机版注册中心
      defaultZone: http://10.14.0.62:8761/eureka
